name: Flask CI

on:
  push:
    branches: [ "task/155-156-automate-linting-and-coverage-with-github-actions" ]
    paths:
      - 'backend/**' # Isolates the changes to the backend
  pull_request:
    branches: [ "main", "task/155-156-automate-linting-and-coverage-with-github-actions" ]
    paths:
      - 'backend/**' # Isolates the changes to the backend
  workflow_dispatch:    

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    # ~~~~~ Sets up the virual environment: ~~~~~
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install ruff pytest-cov

    # Simply check the formatting is correct
    - name: Check formatting standards with Ruff
      working-directory: ./backend
      continue-on-error: true
      run: ruff format --check . # Use ' ruff format . ' to fix styling errors :)

    # Simple linting check using Ruff
    - name: Linting using Ruff
      working-directory: ./backend
      continue-on-error: true
      run: ruff check --output-format=github --target-version=py311 . 

    # Runs all the tests and the returns a table with the percentages of each.py file is accounted for    
    - name: Run tests and generate a coverage report
      working-directory: ./backend
      env:
        FLASK_ENV: testing
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        PYTHONPATH: .
      run: |
        pytest -v -s --cov=app --cov-report=term-missing test/
