name: "Check PR Title"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: PR Title Convention
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |

          REGEX="^\[[A-Z]+\]: .+"
          if [[ ! "$PR_TITLE" =~ $REGEX ]]; then
            echo "::error ::PR title must follow format: [ABC]: Your title"
            exit 1
          fi
          
