name: "Check PR Title"

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  check-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Title Convention
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          REGEX="^\[[A-Z]+\]: .+"
          if [[ ! "$PR_TITLE" =~ $REGEX ]]; then
            echo "::error ::PR title must follow format: [ABC]: Your title"
            exit 1
          fi
  check-closing-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Check Closing Tag
        env:
          PR_CONTENT: ${{github.event.pull_request.body}}
        run: |
          REGEX="^.*Closes #[0-9]+"
          if [[ ! "$PR_CONTENT" =~ $REGEX ]]; then
            echo "::error ::PR body must include a closing tag"
            exit 1
          fi
  check-type-of-change:
    runs-on: ubuntu-latest
    steps:
      - name: Type Of Change is selected
        env:
          PR_CONTENT: ${{github.event.pull_request.body}}
        run: |
          # Looks through lines after header, check if there is a [x] or [X]
          if ! "$PR_CONTENT" | grep -A 7 "Type of Change" | grep -qi "\[[x]\]"; then
            echo "::error ::You must select at least one type of change"
            exit 1
          fi


          
